# Generated by Django 4.1.1 on 2022-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('issued', models.BooleanField(default=False)),
                ('issued_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
    ]
