# Generated by Django 4.1.1 on 2022-09-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='issued_by',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
